name: Makefile CI

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download artifacts
        uses: actions/download-artifact@v2
      - name: display structure of downloaded files
        run: ls -R
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifact/toolchain-darwin.zip
            artifact/toolchain-linux.zip
            artifact/toolchain-win32.zip     

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build toolchain zips
      run: make
    - name: upload artifact zips
      uses: actions/upload-artifact@v2.3.1
      with:
        path: toolchain-*.zip
